const {chromium}=require('playwright-core');const {pathToFileURL}=require('url');const path=require('path');const assert=require('assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--allow-file-access-from-files']});const p=await b.newPage({viewport:{width:780,height:920}});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(pathToFileURL(path.join(__dirname,'app/src/main/assets/index.html')).href+'?test');await p.waitForFunction(()=>window.__siteSDebug?.().splashVisible===false);await p.locator('[data-character="maya"]').click();await p.locator('#startButton').click();
const report=await p.evaluate(async()=>{
 const d={...CharacterDesign.presets.thomas,original:false,hairStyle:'curly',wearBackpack:true};const directions=['down','up','left','right'];let checked=0,minColors=999,hardAlpha=true,uniform=true,walking=true;
 for(const hairStyle of CharacterDesign.enums.hairStyle)for(const wearBackpack of [false,true])for(const direction of directions){const design={...d,hairStyle,wearBackpack};const sprite=CharacterDesign.sprite(design,direction);const pixels=sprite.getContext('2d').getImageData(0,0,32,48).data;const colors=new Set();for(let i=0;i<pixels.length;i+=4){hardAlpha&&=pixels[i+3]===0||pixels[i+3]===255;if(pixels[i+3])colors.add(`${pixels[i]},${pixels[i+1]},${pixels[i+2]}`);}minColors=Math.min(minColors,colors.size);const world=CharacterDesign.worldSprite(sprite);uniform&&=world.width===24&&world.height===32;walking&&=CharacterDesign.sprite(design,direction,0).toDataURL()!==CharacterDesign.sprite(design,direction,1).toDataURL();checked++;}
 const colorsWork=['skin','shirt','pants','backpack','hair'].every(field=>directions.every(f=>CharacterDesign.sprite(d,f).toDataURL()!==CharacterDesign.sprite({...d,[field]:'#dc409a'},f).toDataURL()));
 const optionsWork=['down','left','right'].every(f=>['beard','stubble','moustache'].every(facialHair=>CharacterDesign.sprite({...d,facialHair},f).toDataURL()!==CharacterDesign.sprite({...d,facialHair:'none'},f).toDataURL()));
 const bagWorks=directions.every(f=>CharacterDesign.sprite({...d,wearBackpack:false},f).toDataURL()!==CharacterDesign.sprite(d,f).toDataURL());
 const people=window.__siteSTest.peopleDesigns();const detailedNpcs=people.every(d=>{const c=CharacterDesign.sprite(d);return CharacterDesign.worldSprite(c).height===32;});
 const g=document.createElement('div');g.id='qualityGallery';g.style='position:fixed;inset:0;z-index:300;background:#223b4c;color:white;padding:18px;display:grid;grid-template-columns:repeat(6,1fr);align-content:start;gap:16px;font:12px monospace';
 const designs=[...Object.entries(CharacterDesign.library),...people.slice(0,14).map((d,i)=>[`npc${i}`,d])];
 for(const [id,d]of designs){const box=document.createElement('div');box.style='text-align:center';const c=document.createElement('canvas');c.width=96;c.height=128;c.style='width:96px;height:128px;image-rendering:pixelated';const x=c.getContext('2d');x.imageSmoothingEnabled=false;let source=CharacterDesign.sprite(d);
 if(d.original){const data=window.__siteSTest.walkFrameImage(id,'down','idle');const image=await new Promise(resolve=>{const image=new Image();image.onload=()=>resolve(image);image.src=data;});source=document.createElement('canvas');source.width=image.width;source.height=image.height;source.getContext('2d').drawImage(image,0,0);}
 x.drawImage(CharacterDesign.worldSprite(source),0,0,96,128);const label=document.createElement('div');label.textContent=id.startsWith('npc')?'NPC '+id.slice(3):d.name;box.append(c,label);g.append(box);}document.body.append(g);
 return {templates:Object.keys(CHARACTER_TEMPLATES).length,checked,minColors,hardAlpha,uniform,walking,colorsWork,optionsWork,bagWorks,detailedNpcs,npcCount:people.length};
});assert.equal(report.templates,56);assert.equal(report.checked,56);assert(report.minColors>30);for(const k of ['hardAlpha','uniform','walking','colorsWork','optionsWork','bagWorks','detailedNpcs'])assert(report[k],k);assert.equal(report.npcCount,145);await p.screenshot({path:'docs/preview_detailed_characters_v15.png'});await p.evaluate(()=>document.querySelector('#qualityGallery').remove());await p.setViewportSize({width:390,height:844});await p.screenshot({path:'docs/preview_detailed_npcs_v15.png'});assert.deepEqual(errors,[]);await b.close();console.log('PASS',report);})().catch(e=>{console.error(e);process.exit(1)});
