const {chromium}=require('playwright-core');const {pathToFileURL}=require('url');const path=require('path');const assert=require('assert/strict');
(async()=>{
 const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--allow-file-access-from-files']});
 const page=await browser.newPage({viewport:{width:390,height:844}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(pathToFileURL(path.join(__dirname,'app/src/main/assets/index.html')).href+'?test');await page.waitForFunction(()=>window.__siteSDebug?.().splashVisible===false);
 // Include Continue so all three action buttons are measured.
 await page.locator('#startButton').click();await page.evaluate(()=>window.kaplanSave());await page.reload();await page.waitForFunction(()=>window.__siteSDebug?.().splashVisible===false);
 for(const viewport of [{width:390,height:844},{width:360,height:780},{width:320,height:568},{width:700,height:700}]){
  await page.setViewportSize(viewport);
  const bounds=await page.evaluate(()=>{const picker=document.querySelector('#characterPicker'),r=picker.getBoundingClientRect(),cards=[...picker.children].map(c=>c.getBoundingClientRect()),buttons=[...document.querySelectorAll('.start-actions button')].filter(b=>!b.classList.contains('hidden')).map(b=>b.getBoundingClientRect());return {clipped:cards.some(c=>c.top<r.top||c.bottom>r.bottom),innerScroll:picker.scrollHeight>picker.clientHeight,gaps:buttons.slice(1).map((b,i)=>b.top-buttons[i].bottom),widths:buttons.map(b=>b.width)};});
  assert.equal(bounds.clipped,false,'No card may be clipped inside picker');assert.equal(bounds.innerScroll,false);assert(bounds.gaps.every(g=>Math.abs(g-12)<1));assert(bounds.widths.every(w=>Math.abs(w-bounds.widths[0])<1));
  await page.locator('[data-character="yael"]').scrollIntoViewIfNeeded();assert(await page.locator('[data-character="yael"]').isVisible());await page.locator('#continueButton').scrollIntoViewIfNeeded();
 }
 await page.setViewportSize({width:390,height:844});await page.reload();await page.waitForFunction(()=>window.__siteSDebug?.().splashVisible===false);await page.screenshot({path:'docs/preview_chooser_v10.png'});
 await page.locator('#designCharacterButton').click();await page.waitForFunction(()=>window.__siteSTest.walkFrameImage('andrei','down',0));
 assert.equal(await page.locator('[name="headphones"] option').count(),8);
 for(const type of ['over-ear','on-ear','wired-earbuds','wireless-earbuds','neckband','bone-conduction','gaming-headset']){
  await page.locator('[name="headphones"]').selectOption(type);await page.locator('[name="headphoneColor"]').fill('#f68bce');await page.locator('#designForm button[type=submit]').click();
  const result=await page.evaluate(()=>{const d=CharacterDesign.library.andrei,baseline={...d,headphones:'none'};return {original:d.original,type:d.headphones,color:d.headphoneColor,changed:['down','up','left','right'].every(f=>CharacterDesign.sprite(d,f,0).toDataURL()!==CharacterDesign.sprite(baseline,f,0).toDataURL())};});
  assert.equal(result.original,true,'Headphones must retain original Andrei art');assert.equal(result.type,type);assert.equal(result.color,'#f68bce');assert(result.changed);
 }
 await page.locator('#closeDesigner').click();await page.locator('#continueButton').click();await page.evaluate(()=>window.kaplanSave());await page.reload();await page.waitForFunction(()=>window.__siteSDebug?.().splashVisible===false);await page.locator('#continueButton').click();assert.equal(await page.evaluate(()=>CharacterDesign.library.andrei.headphones),'gaming-headset');
 await page.locator('#menuButton').click();await page.locator('#editCharacterButton').click();await page.locator('[name="headphones"]').selectOption('none');await page.locator('#designForm button[type=submit]').click();assert.equal(await page.evaluate(()=>CharacterDesign.library.andrei.original),true);await page.locator('#closeDesigner').click();
 // Old v0.9 designs migrate to None and retain their original clothing/name.
 await page.evaluate(()=>{localStorage.setItem('kaplan-character-library-v1',JSON.stringify({andrei:{...CharacterDesign.presets.andrei,name:'Saved Andrei',shirt:'#aa5544',headphones:undefined,headphoneColor:undefined}}));});await page.reload();await page.waitForFunction(()=>window.__siteSDebug?.().splashVisible===false);assert.deepEqual(await page.evaluate(()=>{const d=CharacterDesign.library.andrei;return [d.name,d.shirt,d.headphones,d.headphoneColor];}),['Saved Andrei','#aa5544','none','#34465d']);
 await page.evaluate(async()=>{const original=await new Promise(resolve=>{const img=new Image();img.onload=()=>resolve(img);img.src=window.__siteSTest.walkFrameImage('andrei','down',0);});const source=document.createElement('canvas');source.width=original.width;source.height=original.height;source.getContext('2d').drawImage(original,0,0);const g=document.createElement('div');g.id='headphoneGallery';g.style='position:fixed;inset:0;z-index:200;background:#22364b;color:white;display:grid;grid-template-columns:1fr 1fr;gap:12px;padding:20px;overflow:auto';for(const type of CharacterDesign.enums.headphones){const box=document.createElement('div');box.style='text-align:center;font:12px monospace';const c=document.createElement('canvas');c.width=128;c.height=96;c.style='height:96px;width:128px;margin:0 auto;image-rendering:pixelated';const x=c.getContext('2d');x.imageSmoothingEnabled=false;const d={...CharacterDesign.presets.andrei,headphones:type,headphoneColor:'#68b9cf'};x.drawImage(CharacterDesign.withHeadphones(source,d,'down'),0,0,64,80);x.drawImage(CharacterDesign.sprite(d,'left',0),64,0,64,96);const label=document.createElement('p');label.textContent=type;box.append(c,label);g.append(box);}document.body.append(g);});await page.screenshot({path:'docs/preview_headphones_v10.png'});
 assert.deepEqual(errors,[]);await browser.close();console.log('PASS: complete rows, equal gaps/widths at four sizes, seven headphone types/colors/four directions, original art preserved, save/resume and old design migration');
})().catch(e=>{console.error(e);process.exit(1)});
